##################################################################
# CHECK VIVADO VERSION
##################################################################

# set scripts_vivado_version 2018.3
# set current_vivado_version [version -short]

# if { [string first $scripts_vivado_version $current_vivado_version] == -1 } {
#   catch {common::send_msg_id "IPS_TCL-100" "ERROR" "This script was generated using Vivado <$scripts_vivado_version> and is being run in <$current_vivado_version> of Vivado. Please run the script in Vivado <$scripts_vivado_version> then open the design in Vivado <$current_vivado_version>. Upgrade the design by running \"Tools => Report => Report IP Status...\", then run write_ip_tcl to create an updated script."}
#   return 1
# }

##################################################################
# START
##################################################################

# To test this script, run the following commands from Vivado Tcl console:
# source Rx_ReSample_FIR_F5.tcl
# If there is no project opened, this script will create a
# project, but make sure you do not have an existing project
# <./Prj/Prj.xpr> in the current working folder.

set list_projs [get_projects -quiet]
if { $list_projs eq "" } {
  create_project Prj Prj -part xc7z020clg400-2
  set_property target_language Verilog [current_project]
  set_property simulator_language Mixed [current_project]
}

##################################################################
# CHECK IPs
##################################################################

set bCheckIPs 1
set bCheckIPsPassed 1
if { $bCheckIPs == 1 } {
  set list_check_ips { xilinx.com:ip:fir_compiler:7.2 }
  set list_ips_missing ""
  common::send_msg_id "IPS_TCL-1001" "INFO" "Checking if the following IPs exist in the project's IP catalog: $list_check_ips ."

  foreach ip_vlnv $list_check_ips {
  set ip_obj [get_ipdefs -all $ip_vlnv]
  if { $ip_obj eq "" } {
    lappend list_ips_missing $ip_vlnv
    }
  }

  if { $list_ips_missing ne "" } {
    catch {common::send_msg_id "IPS_TCL-105" "ERROR" "The following IPs are not found in the IP Catalog:\n  $list_ips_missing\n\nResolution: Please add the repository containing the IP(s) to the project." }
    set bCheckIPsPassed 0
  }
}

if { $bCheckIPsPassed != 1 } {
  common::send_msg_id "IPS_TCL-102" "WARNING" "Will not continue with creation of design due to the error(s) above."
  return 1
}

##################################################################
# Rx_ReSample_FIR_F5 FILES
##################################################################

proc write_fir_compiler_FIR_F5 { fir_compiler_FIR_F5_filepath } {
  set fir_compiler_FIR_F5 [open $fir_compiler_FIR_F5_filepath  w+]

  puts $fir_compiler_FIR_F5 {; XILINX FIR Compiler FIR 滤波器系数(.COE)文件}
  puts $fir_compiler_FIR_F5 {; Generated by AET_ZY.}
  puts $fir_compiler_FIR_F5 {; Generated on: 2026-02-04 16:50:55}
  puts $fir_compiler_FIR_F5 {Radix = 16;}
  puts $fir_compiler_FIR_F5 {Coefficient_Width = 16;}
  puts $fir_compiler_FIR_F5 {CoefData = }
  puts $fir_compiler_FIR_F5 {001b}
  puts $fir_compiler_FIR_F5 {0031}
  puts $fir_compiler_FIR_F5 {003a}
  puts $fir_compiler_FIR_F5 {002d}
  puts $fir_compiler_FIR_F5 {0000}
  puts $fir_compiler_FIR_F5 {ffb4}
  puts $fir_compiler_FIR_F5 {ff60}
  puts $fir_compiler_FIR_F5 {ff34}
  puts $fir_compiler_FIR_F5 {ff60}
  puts $fir_compiler_FIR_F5 {0000}
  puts $fir_compiler_FIR_F5 {00f9}
  puts $fir_compiler_FIR_F5 {01ee}
  puts $fir_compiler_FIR_F5 {025a}
  puts $fir_compiler_FIR_F5 {01c4}
  puts $fir_compiler_FIR_F5 {0000}
  puts $fir_compiler_FIR_F5 {fd6d}
  puts $fir_compiler_FIR_F5 {faf9}
  puts $fir_compiler_FIR_F5 {f9e1}
  puts $fir_compiler_FIR_F5 {fb57}
  puts $fir_compiler_FIR_F5 {0000}
  puts $fir_compiler_FIR_F5 {0795}
  puts $fir_compiler_FIR_F5 {10d1}
  puts $fir_compiler_FIR_F5 {19ba}
  puts $fir_compiler_FIR_F5 {202d}
  puts $fir_compiler_FIR_F5 {2288}
  puts $fir_compiler_FIR_F5 {202d}
  puts $fir_compiler_FIR_F5 {19ba}
  puts $fir_compiler_FIR_F5 {10d1}
  puts $fir_compiler_FIR_F5 {0795}
  puts $fir_compiler_FIR_F5 {0000}
  puts $fir_compiler_FIR_F5 {fb57}
  puts $fir_compiler_FIR_F5 {f9e1}
  puts $fir_compiler_FIR_F5 {faf9}
  puts $fir_compiler_FIR_F5 {fd6d}
  puts $fir_compiler_FIR_F5 {0000}
  puts $fir_compiler_FIR_F5 {01c4}
  puts $fir_compiler_FIR_F5 {025a}
  puts $fir_compiler_FIR_F5 {01ee}
  puts $fir_compiler_FIR_F5 {00f9}
  puts $fir_compiler_FIR_F5 {0000}
  puts $fir_compiler_FIR_F5 {ff60}
  puts $fir_compiler_FIR_F5 {ff34}
  puts $fir_compiler_FIR_F5 {ff60}
  puts $fir_compiler_FIR_F5 {ffb4}
  puts $fir_compiler_FIR_F5 {0000}
  puts $fir_compiler_FIR_F5 {002d}
  puts $fir_compiler_FIR_F5 {003a}
  puts $fir_compiler_FIR_F5 {0031}
  puts $fir_compiler_FIR_F5 {001b}

  flush $fir_compiler_FIR_F5
  close $fir_compiler_FIR_F5
}

##################################################################
# CREATE IP Rx_ReSample_FIR_F5
##################################################################

set fir_compiler Rx_ReSample_FIR_F5
create_ip -name fir_compiler -vendor xilinx.com -library ip -version 7.2 -module_name $fir_compiler

write_fir_compiler_FIR_F5  [file join [get_property IP_DIR [get_ips $fir_compiler]] FIR_F5.coe]
set_property -dict { 
  CONFIG.CoefficientSource {COE_File}
  CONFIG.Coefficient_File {FIR_F5.coe}
  CONFIG.Coefficient_Sets {1}
  CONFIG.Coefficient_Sign {Signed}
  CONFIG.Quantization {Integer_Coefficients}
  CONFIG.Coefficient_Width {16}
  CONFIG.Coefficient_Fractional_Bits {0}
  CONFIG.Coefficient_Structure {Inferred}
  CONFIG.Data_Width {16}
  CONFIG.Output_Width {33}
  CONFIG.Has_ARESETn {true}
} [get_ips $fir_compiler]

##################################################################

